// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pekbbcvacgvnkiogtoca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBla2JiY3ZhY2d2bmtpb2d0b2NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTIxMzAsImV4cCI6MjA2MzQyODEzMH0.dAXbGyzvoN1GykuMTO7BA6QWWvmD0WYhT-ZAuzblaT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);